Added Out-of-Band User Entered Data Mitigation
oauth-wg/oauth-cross-device-security pull request #101
Opened 2023-09-15 15:38 UTC by PieterKas

See #85 Bind QR Code to User Info

2023-09-15 15:58 UTC, marcopernpruner requested changes
Fix typos, consistency on "Authorization Device"

2023-09-15 15:58 UTC, marcopernpruner commented on draft-ietf-oauth-cross-device-security.md
> +In the User-Transferred Session Data Pattern, users MAY enter out-of-band information on the Initiating Device to start the authorization process. The out-of-band data entered by the user MAY then be
```suggestion
In the User-Transferred Session Data Pattern, users MAY enter out-of-band information on the Initiating Device to start the authorization process. The out-of-band data entered by the user MAY then be included in the QR code which is displayed on the Initiating Device. When the QR code is scanned by the Authorization Device, the out-of-band data is verified by the user or by the Authorization Device. The out-of-band data could be any attribute that the user or Authorization Device can retrieve during the authorization process. Examples include a serial number, one-time password or PIN, location or any other data that the user or the Authorization Device can recall or retrieve during the authorization process ([@MPRCS2020], [@PCRSM2023]).
```

2023-09-15 18:31 UTC, PieterKas commented on draft-ietf-oauth-cross-device-security.md
> +In the User-Transferred Session Data Pattern, users MAY enter out-of-band information on the Initiating Device to start the authorization process. The out-of-band data entered by the user MAY then be
Thanks @marcopernpruner !

2023-09-22 14:13 UTC, danielfett approved these changes

2023-09-22 14:16 UTC, merged